exports.ERROR_MESSAGE = {
    SOMETHING_WENT_WRONG:"Something Went Wrong",
    OTP_NOT_VERIFIED: "otp not verified",
    REQ_MOB_MESS:"Mobile number and message are required.",
    NO_NOT_EXIST: "Mobile not doesn't exist",
    OTP_NOT_VERIFIED: "OTP not verified",
    OTP_NOT_FOUND:"OTP not found",
    OTP_EXPIRED:"OTP expired",
    INVALID_OTP: "Invalid Otp",
    USER_ALREADY:"User already registered",
    PHONE_NO_REQ:"Phone number is required",
    PHONE_OTP_REQ:"Phone, Email and both OTPs are required.",
    EMAIL_REQUIRED: "Email is required",
    PHONE_EMAIL_REQ:"Phone and Email are required.",
    PHONE_ALREADY_EXISTS: "Phone number is already registered.",
    EMAIL_ALREADY_EXISTS: "Email is already registered.",
    ROLE_ALREADY_EXISTS: "Role already exists",
    ROLE_NOT_FOUND: "Role not found",
    ROLE_ID_REQUIRED: "Role ID is required",
    ROLE_NAME_REQUIRED: "Role name is required",
    USER_ALREADY_EXISTS: "User already exists",
    USER_NOT_FOUND: "User not found",
    PLAN_ALREADY_EXISTS: "Plan already exists",
    PLAN_NOT_FOUND: "Plan not found",
    INVALID_CREDENTIALS: "Invalid credentials",
    UNAUTHORIZED_SUPERADMIN: "Unauthorized SuperAdmin",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    UNAUTHORIZED: "Unauthorized",
    ACCOUNT_NOT_FOUND: "Account not found",
    ACCOUNT_ID_REQUIRED: "Account ID is required",
    MEMBER_ID_REQUIRED: "Member ID is required",
    TOKEN_NOT_FOUND:"Unauthorized & Token Not Found",
    TOKRN_MISSING: "Unauthorized & Token Missing",
    TOKEN_RELETED_ERROR: "tOKEN Related Error",
    SUPERaDMIN_CHECK_ERROR: "SuperAdmin check error",
    YOUR_ROLE_NOT_FOUND: "Your role not found",
    YOUR_ROLE_NOT_MATCH: "Your role does not match the required roles",
    YOUR_ROLE_CHECK_ERROR: "Your role check error",

    
    


};

exports.SUCCESS_MESSAGE = {
    SUCCESS: 'Success',
    OTP_GENERATED_SUCCESSFULLY: 'OTP generated successfully',
    OTP_VERIFIED_SUCCESSFULLY: 'OTP verified successfully',
    USER_LOGGED_IN_SUCCESSFULLY: 'User logged in successfully',
    OTP_SUCESS:"OTP sent successfully",
    SIGNUP_SUCESS:"Signup successful",
    ROLE_CREATED: "Role created successfully",
    ROLE_UPDATED: "Role updated successfully",
    ROLE_DELETED: "Role deleted successfully",
    ROLE_FETCHED: "Roles fetched successfully",
    PLAN_CREATED_SUCCESSFULLY: "Plan created successfully",
    PLANS_FETCHED_SUCCESSFULLY: "All Plans fetched successfully",
    PLAN_FETCHED_SUCCESSFULLY: "Plan fetched successfully",
    PLAN_UPDATED_SUCCESSFULLY: "Plan updated successfully",
    PLAN_DELETED_SUCCESSFULLY: "Plan deleted successfully",
    ACCOUNT_DELETED_SUCCESSFULLY: "Account deleted successfully",
    ACCOUNT_CREATED_SUCCESSFULLY: "Account created successfully",
    ACCOUNTS_FETCHED_SUCCESSFULLY: "Accounts fetched successfully",
    ACCOUNT_UPDATED_SUCCESSFULLY: "Account updated successfully",
    ACCOUNT_FETCHED_SUCCESSFULLY: "Account fetched successfully",
    ACCOUNT_DELETED_SUCCESSFULLY: "Account deleted successfully",

};